### PR TITLE
US 17 -  Additional Engines

### PR DESCRIPTION
**Pull request by Zerthox**
# Purpose
This makes Stockfish, Multi-Variant-Stockfish & Fairy-Stockfish available as Engine. The user may select one of the engines supporting the current variant. By default Stockfish is used for the variants it supports, otherwise Multi-Variant-Stockfish if it supports the variant and Fairy-Stockfish for the remaining variants.

# Pre-merge TODOs and Checks 
- [x] PGN file loads correctly
- [x] Navigating through the move history works
- [x] Starting the engine shows moves (test for both sides)
- [x] Selecting a different variant loads a new board with the variant and you can make moves on the board
- [x] In Crazyhouse the pocket pieces are shown and you can drop pieces

### CODE REVIEW

**Comment by Zerthox** [comment]
Currently the last selected engine is saved per variant. Meaning if the user selects Multi-Variant-Stockfish in Standard and swaps to Crazyhouse, the engine will change to the default for Crazyhouse, Stockfish. This could be a bit counterintuitive, so maybe we want to keep the currently select engine as long as it supports the next variant?

**Comment by Zerthox** [comment]
Changed the engine switching logic so when the user switches to a different variant we use:
1. The last engine the user had selected for that variant, or else...
2. The current engine if it supports the new variant, or else...
3. The default engine for the new variant (first engine in list that supports the variant)

**Comment by Zerthox** [comment]
I believe this is will also fix #18.

**Comment by Zerthox** [comment]
The postinstall script to download engine binaries has been merged into this branch. This should be ready for review now.

**Comment by MartinRuz** [comment]
In EvalPlot you use a mapGetter for points, but it doesnt have a getter in store, resulting in an error

**Pull request merged**
