### PR TITLE
Engine perfomance improvements

### PR DESCRIPTION
**Pull request by Zerthox**
This aims to improve performance while the engine is running. Summary of the changes:
- The engine driver has moved from the main process to a worker thread in the renderer to speed up messaging.
- Messages in the worker thread are cached and only sent at a maximum interval of 50ms to avoid blocking the renderer with incoming messages. We can look into adjusting this frequency in the future.
- The engine console has been readded to the UI and now makes use of lazy loading. I've tried using multiple premade components, but settled for writing a custom solution since none of them really fit our needs. As of right now, only the visible lines plus a buffer of 10 above & 10 below is rendered.
- Engine IO is no longer saved in the store. It is consumed directly in the EngineConsole component to avoid unnecessary store updates.

Currently I'm abusing an empty mutation in the store to notify the EngineConsole component about clearing the console. Maybe we can figure out something better.

Note: #86 has to be merged before this, since I based my branch off of its branch in order to enforce the new lint rules.

### CODE REVIEW

**Comment by Zerthox** [comment]
This also closes #27 since the console is working correctly now.

**Comment by MartinRuz** [comment]
the engine console now receives quite a lot of updates, which is distracting, maybe limit the console output of the same type? or don't print move updates unless the user specifies that he wants this, as we have the engine lines in the pvline panel.
Also when scrolling up the automatic down scrolling does not stop, this is not expected behavior imo

**Comment by Zerthox** [comment]
I've started to implement more intuitive auto scroll.

Always filtering out certain engine output seems like a bad idea, engine developers may need to access the full log.
But we could add filter settings or some kind of search to the console, to make the potentially massive output easier to work with.

**Comment by Zerthox** [comment]
> Currently I'm abusing an empty mutation in the store to notify the EngineConsole component about clearing the console. Maybe we can figure out something better.

While looking through the code for the UI improvements I've seen that we had similar situations in other parts of the project. Since Vuex does expose a nice interface for communication vie events, maybe we should agree on a main event emitter bus to use?

This could be done via the the NodeJS [EventEmitter](https://nodejs.org/api/events.html#events_class_eventemitter) class. Alternatively we could use the [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget) DOM interface with [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) events.

**Review by MartinRuz — APPROVED** [review]

**Pull request merged**
