### PR TITLE
Bug fixes

### LINKED ISSUE #185: Support 3check pasting of other FEN variants
- `LiGround` currently only supporst `3check` FENs like this: 

      rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 3+3 0 1

- It would be nice, if `LiGround` would also support the same position, but in a slightly different FEN that is widely used (e.g. by `lichess.org`). In this notation the same position would be 

      rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 +0+0

### PR DESCRIPTION
**Pull request by ksthicke**
# Purpose
Fixes a couple bugs.
1. Makes the arrow keys work when the checkbox is in focus.
2. (not a bug) Removes unused code.
3. Upgrades ffish, which fixes #185 

# Pre-merge TODOs and Checks 
- [x] PGN file loads correctly
- [x] Navigating through the move history works
- [x] Starting the engine shows moves (test for both sides)
- [x] Selecting a different variant loads a new board with the variant and you can make moves on the board
- [x] In Crazyhouse the pocket pieces are shown and you can drop pieces

### CODE REVIEW

**Comment by ksthicke** [comment]
It looks like it didn't pass the check because I've always been having to use --legacy-peer-deps in order to get it to build.  I'm probably just doing something stupid, but using npm and dealing with dependencies is very new to me.

**Comment by QueensGambit** [comment]
Thanks for the updates. I see, should we remove `package-lock.json` in this case to fix the lint issue?

**Comment by ksthicke** [comment]
Whatever you did with package-lock.json seems to have worked -- thanks!

**Comment by QueensGambit** [comment]
Great, that it works now.
I set `ffish": "^0.7.6` and run `npm install` locally.
Next, I uploaded the resulting `package-lock.json` file.

**Pull request merged**
