### PR TITLE
US5 - Engine Settings

### LINKED ISSUE #22: Engine Settings - US_5
Description:
As a user I want to be able to change the engine settings to be able to use it to its fullest extend.

Acceptance Criteria:
The engine settings can be adjusted in a separate window. The changed settings will be submitted to the engine.

### PR DESCRIPTION
**Pull request by Zerthox**
# Purpose
Opening another pull request for #95 as it had to be reverted. This will close #22.

# Pre-merge TODOs and Checks 
- [x] PGN file loads correctly
- [x] Navigating through the move history works
- [x] Starting the engine shows moves (test for both sides)
- [x] Selecting a different variant loads a new board with the variant and you can make moves on the board
- [x] In Crazyhouse the pocket pieces are shown and you can drop pieces

### CODE REVIEW

**Comment by Zerthox** [comment]
I'll help pushing this forward.

**Comment by BododB** [comment]
When changing a certain setting and then choosing cancel and reselecting the settings tab the changed number is displayed instead of the actual current setting of the engine

**Comment by Zerthox** [comment]
I'll add a fix for #120 in this.

**Comment by BododB** [comment]
Currently i can write any number into the settings like "-1.1" for the number of threads. And the incorrect number is saved.

**Pull request merged**
