### PR TITLE
feature: add a new style inherited from hnz

### PR DESCRIPTION
**Pull request by xiaoyifang**
# Purpose
add a new style of xiangqi which is used mostly in China Mainland

image

# Pre-merge TODOs and Checks 
- [x] _(exclude checks that are not relevant for your feature)_
- [ ] PGN file loads correctly
- [ ] Navigating through the move history works
- [x] Starting the engine shows moves (test for both sides)
- [x] Selecting a different variant loads a new board with the variant and you can make moves on the board
- [ ] In Crazyhouse the pocket pieces are shown and you can drop pieces

### CODE REVIEW

**Comment by QueensGambit** [comment]
Hello @xiaoyifang ,
thank you for your addition. 👍 
Can you keep the `package-lock.json` file?
It is recommended to keep `package-lock.json` versioned in git:
* https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore
* https://stackoverflow.com/questions/44646719/does-package-lock-json-need-to-be-versioned-in-git

**Comment by xiaoyifang** [comment]
Do you mean I should not commit the `package-lock.json` file

**Comment by xiaoyifang** [comment]
to make it simple ,as I have not changed any dependencies ,I just removed the changes of package-lock.json

**Comment by QueensGambit** [comment]
Thank you @xiaoyifang . Yes, that's what I meant.

**Pull request merged**
